OakIntroSpeech_Part1::
# 1 "data/text/oak_speech.pory"
	.string "Hello, there! Welcome to Sapphica!\p"
	.string "The queer capital of the Pokémon\n"
	.string "World!\l"
	.string "$"

OakIntroSpeech_Part2::
# 5 "data/text/oak_speech.pory"
	.string "This region is teeming with a wide\n"
	.string "plethora of pokémon and people...\l"
	.string "$"

OakIntroSpeech_Part3::
# 9 "data/text/oak_speech.pory"
	.string "You may have heard of me. I’m\n"
	.string "Professor Oak, a pokémon\l"
	.string "researcher.\l"
	.string "$"

OakIntroSpeech_Part4::
# 13 "data/text/oak_speech.pory"
	.string "I’ve come all the way from Kanto to\n"
	.string "discover what attracts so many\l"
	.string "different types of pokémon to this\l"
	.string "rather fascinating region.\p"
	.string "Now then...\l"
	.string "$"

OakIntroSpeech_Part5::
# 17 "data/text/oak_speech.pory"
	.string "We'll be neighbors soon so...\p"
	.string "Why don't you tell me a little about\n"
	.string "yourself?\l"
	.string "$"

OakIntroSpeech_Part6::
# 21 "data/text/oak_speech.pory"
	.string "What kind of person are you?$"

OakIntroSpeech_Unsure::
# 25 "data/text/oak_speech.pory"
	.string "Oh, really?\p"
	.string "Well, hopefully living here will give\n"
	.string "you a chance to figure things\l"
	.string "out...\p"
	.string "So, what should I call you?\l"
	.string "$"

OakIntroSpeech_Queer::
# 29 "data/text/oak_speech.pory"
	.string "That's splendid!\p"
	.string "I’m sure you’ll have an amazing time\n"
	.string "living and adventuring here then!\p"
	.string "So, what should I call you?\l"
	.string "$"

OakIntroSpeech_Part7::
# 33 "data/text/oak_speech.pory"
	.string "Oh, that fits you nicely.\p"
	.string "So your name is {PLAYER}?$"

OakIntroSpeech_Part8::
# 37 "data/text/oak_speech.pory"
	.string "This is my grandchild.\l"
	.string "They've been going through a lot\n"
	.string "lately...\p"
	.string "I feel awful but I can't quite\n"
	.string "remember what name they're using...\p"
	.string "I think their name is...$"

OakIntroSpeech_GrandchildNameWrong::
# 41 "data/text/oak_speech.pory"
	.string "No that's not right.\n"
	.string "I think their name is actually...$"

OakIntroSpeech_GrandchildNameRight::
# 45 "data/text/oak_speech.pory"
	.string "Yes, that sounds right.\n"
	.string "Their name is {RIVAL}.\p"
	.string "I think the two of you could become\n"
	.string "great friends.\l"
	.string "$"

OakIntroSpeech_Part9::
# 49 "data/text/oak_speech.pory"
	.string "Alright, I’m sure you’re eager to\n"
	.string "start your new life here.\p"
	.string "If you stop by my lab later, I’ll\n"
	.string "give you your very own pokémon.\p"
	.string "I'm sure the two of you will become\n"
	.string "a fabulous team someday.\p"
	.string "Ok, I won't keep you any longer. See\n"
	.string "you later {PLAYER}!\p"
	.string "Good luck on your adventures!\l"
	.string "$"
